## Part 1: Preprocessing

In [15]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [23]:
print(attrition_df.dtypes)

# Determine the number of unique values in each column
attrition_df.nunique().sort_values(ascending=False)

Age                          int64
Attrition                   object
BusinessTravel              object
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EnvironmentSatisfaction      int64
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
NumCompaniesWorked           int64
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object


HourlyRate                  71
Age                         43
TotalWorkingYears           40
YearsAtCompany              37
DistanceFromHome            29
YearsInCurrentRole          19
YearsWithCurrManager        18
YearsSinceLastPromotion     16
PercentSalaryHike           15
NumCompaniesWorked          10
JobRole                      9
TrainingTimesLastYear        7
EducationField               6
JobLevel                     5
Education                    5
EnvironmentSatisfaction      4
JobInvolvement               4
JobSatisfaction              4
RelationshipSatisfaction     4
StockOptionLevel             4
WorkLifeBalance              4
Department                   3
BusinessTravel               3
MaritalStatus                3
OverTime                     2
Attrition                    2
PerformanceRating            2
dtype: int64

In [17]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()

Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [24]:
# Create a list of at least 10 column names to use as X data
selected_columns = [
    "Age","DistanceFromHome","Education","EnvironmentSatisfaction",
    "HourlyRate","JobInvolvement","JobLevel","JobSatisfaction",
    "NumCompaniesWorked","PercentSalaryHike"
]

# Create X_df using your selected columns
X_df = attrition_df[selected_columns]

# Show the data types for X_df
X_df.dtypes


Age                        int64
DistanceFromHome           int64
Education                  int64
EnvironmentSatisfaction    int64
HourlyRate                 int64
JobInvolvement             int64
JobLevel                   int64
JobSatisfaction            int64
NumCompaniesWorked         int64
PercentSalaryHike          int64
dtype: object

In [25]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=37)


In [26]:
# Convert your X data to numeric data types however you see fit
X_numeric = pd.get_dummies(X_df)

# Add new code cells as necessary
X_numeric.head()

Age  DistanceFromHome  Education  EnvironmentSatisfaction  HourlyRate  \
0   41                 1          2                        2          94   
1   49                 8          1                        3          61   
2   37                 2          2                        4          92   
3   33                 3          4                        4          56   
4   27                 2          1                        1          40   

   JobInvolvement  JobLevel  JobSatisfaction  NumCompaniesWorked  \
0               3         2                4                   8   
1               2         2                2                   1   
2               2         1                3                   6   
3               3         1                3                   1   
4               3         1                2                   9   

   PercentSalaryHike  
0                 11  
1                 23  
2                 15  
3                 11  
4                 12

In [31]:
# Create a StandardScaler
std_scaler = StandardScaler()

# Fit the StandardScaler to the training data
std_scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = std_scaler.transform(X_train)
X_test_scaled = std_scaler.transform(X_test)



In [32]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
dept_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
one_hot_dept_encoded = dept_encoder.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_dept_encoded = dept_encoder.transform(y_train[['Department']])
y_test_dept_encoded = dept_encoder.transform(y_test[['Department']])

display(y_train_dept_encoded)
display(y_test_dept_encoded)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0

In [33]:
# Create a OneHotEncoder for the Attrition column
attr_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
attr_encoder.fit(y_train[['Attrition']])


# Create two new variables by applying the encoder
# to the training and testing data
y_train_attr_encoded = attr_encoder.transform(y_train[['Attrition']])
y_test_attr_encoded = attr_encoder.transform(y_test[['Attrition']])

display(y_train_attr_encoded)
display(y_test_attr_encoded)

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]])

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.

## Part 2: Create, Compile, and Train the Model

In [34]:
# Find the number of columns in the X training data
x_input_dim = X_train_scaled.shape[1]

# Create the input layer
input_layer = layers.Input(shape=(x_input_dim,))

# Create at least two shared layers
shared_layer1 = layers.Dense(64, activation='relu')(input_layer)
shared_layer2 = layers.Dense(32, activation='relu')(shared_layer1)

In [35]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
dept_hidden_layer = layers.Dense(16, activation='relu')(shared_layer2)

# Create the output layer
dept_output_layer = layers.Dense(y_train_dept_encoded.shape[1], activation='softmax', name='department_output')(dept_hidden_layer)



In [36]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attr_hidden_layer = layers.Dense(16, activation='relu')(shared_layer2)

# Create the output layer
attr_output_layer = layers.Dense(y_train_attr_encoded.shape[1], activation='softmax', name='attrition_output')(attr_hidden_layer)


In [37]:
# Create the model
new_model = Model(inputs=input_layer, outputs=[dept_output_layer, attr_output_layer])

# Compile the model
new_model.compile(optimizer='adam', 
              loss={'department_output': 'categorical_crossentropy', 'attrition_output': 'categorical_crossentropy'}, 
              metrics={'department_output': 'accuracy', 'attrition_output': 'accuracy'})

# Summarize the model
new_model.summary()


Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 10)]         0           []                               
                                                                                                  
 dense (Dense)                  (None, 64)           704         ['input_1[0][0]']                
                                                                                                  
 dense_1 (Dense)                (None, 32)           2080        ['dense[0][0]']                  
                                                                                                  
 dense_2 (Dense)                (None, 16)           528         ['dense_1[0][0]']                
                                                                                              

In [38]:
# Train the model
training = new_model.fit(
    X_train_scaled, 
    {'department_output': y_train_dept_encoded, 'attrition_output': y_train_attr_encoded},
    epochs=50,
    batch_size=32,
    validation_data=(X_test_scaled, {'department_output': y_test_dept_encoded, 'attrition_output': y_test_attr_encoded}),
    verbose=1
)

Epoch 1/50
37/37 [==============================] - 1s 12ms/step - loss: 1.4932 - department_output_loss: 0.9180 - attrition_output_loss: 0.5752 - department_output_accuracy: 0.6131 - attrition_output_accuracy: 0.7321 - val_loss: 1.2817 - val_department_output_loss: 0.8327 - val_attrition_output_loss: 0.4491 - val_department_output_accuracy: 0.6531 - val_attrition_output_accuracy: 0.8435
Epoch 2/50
37/37 [==============================] - 0s 3ms/step - loss: 1.2362 - department_output_loss: 0.7971 - attrition_output_loss: 0.4391 - department_output_accuracy: 0.6539 - attrition_output_accuracy: 0.8376 - val_loss: 1.2157 - val_department_output_loss: 0.7942 - val_attrition_output_loss: 0.4215 - val_department_output_accuracy: 0.6531 - val_attrition_output_accuracy: 0.8435
Epoch 3/50
37/37 [==============================] - 0s 3ms/step - loss: 1.1944 - department_output_loss: 0.7748 - attrition_output_loss: 0.4196 - department_output_accuracy: 0.6539 - attrition_output_accuracy: 0.8376 - 

In [39]:
# Evaluate the model with the testing data
new_model_evaluation = new_model.evaluate(
    X_test_scaled,
    {'department_output': y_test_dept_encoded, 'attrition_output': y_test_attr_encoded},
    verbose=1
)


10/10 [==============================] - 0s 2ms/step - loss: 1.3650 - department_output_loss: 0.8966 - attrition_output_loss: 0.4683 - department_output_accuracy: 0.6190 - attrition_output_accuracy: 0.8299


In [ ]:
# Print the accuracy for both department and attrition
print(new_model_evaluation)

# Extract the specific metrics
test_loss = new_model_evaluation[0]
department_output_loss = new_model_evaluation[1]
attrition_output_loss = new_model_evaluation[2]

print(f"Test Loss: {test_loss}")
print(f"Test Department Output Loss: {department_output_loss}")
print(f"Test Attrition Output Loss: {attrition_output_loss}")

# Calculate accuracy for the department output
dept_pred = new_model.predict(X_test_scaled)[0]
dept_accuracy = np.mean(np.argmax(dept_pred, axis=1) == np.argmax(y_test_dept_encoded, axis=1))

# Calculate accuracy for the attrition output
attr_pred = new_model.predict(X_test_scaled)[1]
attr_accuracy = np.mean(np.argmax(attr_pred, axis=1) == np.argmax(y_test_attr_encoded, axis=1))

print(f"Test Department Output Accuracy: {dept_accuracy}")
print(f"Test Attrition Output Accuracy: {attr_accuracy}")

[1.3649731874465942, 0.8966377973556519, 0.46833536028862, 0.6190476417541504, 0.8299319744110107]
Test Loss: 1.3649731874465942
Test Department Output Loss: 0.8966377973556519
Test Attrition Output Loss: 0.46833536028862
10/10 [==============================] - 0s 1ms/step
Test Department Output Accuracy: 0.6190476190476191
Test Attrition Output Accuracy: 0.8299319727891157


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. - **No.** Accuracy is not always the best metric because accuracy has difficulty in taking in account for class imbalances.  For example, if the number attrition of employees is low compared to employees who stay, much smaller than those who stay, the accuracy can show an inbalance.
2. - **Softmax.** For both `department_output` and `attrition_output`. The choice of Softmax is the support of a multi-class classification in the `department_output` to scale the outputs that will sum to a total of 1.
3. - **More Data:** Increase the amount of training data to improve model generalization.
   - **Hyperparameter Tuning:** Adjusting the learning rates, batch sizes, and the number of layers.
   - **Different Models:** Experiment with different neural network models.